using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OAI.Packets.Events.System
{
    /**
     * Alarm Generation – AG
     * 
     * Occurs whenever an alarm is generated. By default, the alarm generation 
     * event is disabled by system filtering. To enable alarm generation events, 
     * enable system filtering using one of the following commands: _MS (see 
     * page 130), _MA (see page 136), or _CE (see page 105). To verify the bit 
     * is set, send the _QE command, which returns the new bit in the confirmation.
     * 
     * AG,<Resync_Code>,<Mon_Cross_Ref_ID>,<System_ID>,<Network_Node_Number>,
     * <Affected_Ext>,<Alarm_Number>,<Alarm_Text>,<Unique_ID>
     */
    public class OAIAlarmGeneration : OAISystem
    {
        public const string EVENT = "AG";

        public OAIAlarmGeneration(string[] parts) : base(parts) { }
        public OAIAlarmGeneration(byte[] bytes) : base(bytes) { }

        /**
         * System_ID
         * 
         * Indicates where the alarm was generated. Possible values include:
         *      1= The alarm was generated by the communications system.
         *      2 = The alarm was generated by the CT Gateway.
         */
        public string SystemID()
        {
            return Part(4);
        }

        /**
         * Network_Node_Number
         * 
         * Indicates the communications system node number if the alarm
         * is generated by the communications system (<System_ID> =1). 
         * Possible values include:
         *      N = The system is networked, and the node number is displayed.
         *      1 = The system is not networked.
         *      0 = The alarm was generated by the CT Gateway.
         */
        public string NetworkNodeNumber()
        {
            return Part(5);
        }

        /**
         * Affected_Ext
         * 
         * Indicates the extension number of the device associated with 
         * the alarm or the station that cleared the alarm. This field 
         * is empty if the affected extension cannot be determined.
         */
        public string AffectedExt()
        {
            return Part(6);
        }

        /**
         * Alarm_Number
         * 
         * Indicates the alarm number. Refer to the Message Print Diagnostics
         * Manual (part number 550.8018) for a list of alarm numbers and their 
         * corresponding descriptions.
         * 
         * If the alarm is for the CT Gateway, it is a 3-digit number with the 
         * following possible conditions:
         * 
         * #        Alarm Text
         * 001      OAI App(AppNum) AppName(AppName) IPAddr(IpAddr) has dropped its connection.
         * 002      OAI App(AppNum) AppName(AppName) IPAddr(IpAddr) attempted to logon with an
         *          invalid password.
         * 003      OAI App(AppNum) AppName(AppName) IPAddr(IpAddr) has not sent a command
         *          within the required keep-alive period.
         * 004      Switch Connection(ConnectionNum) Node(NodeNum) IpAddress(IpAddr) has
         *          dropped its connection.
         * 005      Switch Connection(ConnectionNum) Node(NodeNum) IpAddress(IpAddr) has failed
         *          to respond to a NOP.
         * 006      Switch Connection(ConnectionNum) Node(NodeNum) IpAddress(IpAddr) connection
         *          has reset.
         * 007      Switch Connection(ConnectionNum) Node(NodeNum) IpAddress(IpAddr) is a
         *          duplicate node.
         * 008      Switch Connection(ConnectionNum) Node(NodeNum) IpAddress(IpAddr) sent a
         *          Ports Exceeded.
         * 009      Switch Connection(ConnectionNum) Node(NodeNum) IpAddress(IpAddr) sent an
         *          Invalid Password Response.
         * 010      Switch Connection(ConnectionNum) Node(NodeNum) IpAddress(IpAddr) detected a
         *          sequence error.
         * 011      Switch Connection(ConnectionNum) Node(NodeNum) IpAddress(IpAddr) detected
         *          invalid OAI data.
         * 012      Switch Connection(ConnectionNum) Node(NodeNum) IpAddress(IpAddr) is an
         *          invalid connection to a CT Gateway.
         * 013      Switch Connection(ConnectionNum) Node(NodeNum) IpAddress(IpAddr) has an
         *          Invalid OAI Protocol.
         * 014      Switch Connection(ConnectionNum) Node(NodeNum) IpAddress(IpAddr) has an
         *          Invalid OAI Level 2 Protocol.
         */
        public string AlarmNumber()
        {
            return Part(7);
        }

        /**
         * Alarm_Text
         * 
         * Indicates the description of the alarm and matches the text generated by
         * Message Print. Refer to the Message Print Diagnostics Manual (part number 
         * 550.8018) for a list of alarm numbers and their corresponding descriptions.
         */
        public string AlarmText()
        {
            return Part(8);
        }

        /**
         * Unique_ID
         * 
         * Indicates a system-generated ID that is specific to the alarm. 
         * Applications use this ID to determine exactly when each alarm 
         * clears. Because this ID is only unique within a node, alarms 
         * on different nodes can have conflicting IDs.
         */
        public string UniqueID()
        {
            return Part(9);
        }

        public new void Process()
        {
            // TODO
        }
    }
}
