using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OAI.Packets.Events.Misc
{
    /**
     * Station Message Recording – SMR 
     * 
     * Occurs whenever SMDR is generated by call processing.
     * 
     * The application must enable a system monitor on the node (or nodes) 
     * with the correct filter mask enabled. A new system filter bit has 
     * been added and can be supplied as part of the _MS, _MA, or _CE commands.
     * 
     * SMR,<Resync_Code>,<Mon_Cross_Ref_ID>,<Node_Number>,<SMDR_INFO>
     */
    public class OAIStationMessageRecording : OAIMisc
    {
        public const string EVENT = "SMR";

        public OAIStationMessageRecording(string[] parts) : base(parts) { }
        public OAIStationMessageRecording(byte[] bytes) : base(bytes) { }

        /**
         * 4 - Node_Number
         * 
         * Indicates the node number that is reporting the SMDR information. This is
         * the node number from which the SMDR information is being sent. This might 
         * not be the node where the SMDR data originally came from because nodes can 
         * route the SMDR data to another node for reporting. To illustrate the 
         * differences in the SMR event outcome, see the following example.
         * 
         * If an SMDR event is created on Node 4 (5000 CP v03.20), and it is routed 
         * to Node 3 (Inter-Tel Axxess v09.00), and then routed to Node 1, the SMR 
         * event will report Node 3 and not Node 4.
         * 
         * If the SMR event is initiated by Node 3, and then routed to Node 4 and 
         * then to Node 1 or directly to Node 1, the SMR event will report Node 3. 
         * 
         * The way to guarantee the correct node number value in the SMR event is 
         * to either have each node directly connected to the reporting node (which 
         * is easy if all the nodes are connected via TCP/IP) or upgrade all the 
         * nodes to the latest version.
         */
        public string Node_Number()
        {
            return Part(4);
        }

        /**
         * 5 - SMDR_INFO
         * 
         * Specifies a || delimited field that contains the data normally sent out 
         * of the SMDR port.
         */
        public string SMDR_INFO()
        {
            return Part(5);
        }

        public new void Process()
        {
            // TODO
        }
    }
}
